server:
  port: 8082
spring:
  application:
    name: employee-service  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
